version: '3'
services:
  pyside6:
    restart: always
    build: .
    container_name: 'mokumoku_pyside6'
    working_dir: '/home/worker/'
    tty: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
    #  - $HOME/works/py_works:/home/worker/py_works
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./apps:/home/worker/apps
      
