version: '3'
services:
  pyside6:
    restart: always
    build: .
    container_name: 'mokumoku_pyside6'
    hostname: 'mokumoku_pyside6'
    working_dir: '/home/worker/'
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - $HOME/works/mokumoku_books:/home/worker/mokumoku_books
      #- /tmp/.X11-unix:/tmp/.X11-unix
      - ./apps:/home/worker/apps
      
